"""Initial Schema

Revision ID: f95041726f3d
Revises: 
Create Date: 2024-01-08 01:40:18.086722+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95041726f3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.Text(), nullable=False),
    sa.Column('judgement_points', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.Column('net_points', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earning_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_channel_id', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_lodged', sa.Integer(), nullable=True),
    sa.Column('act_summary', sa.Text(), nullable=True),
    sa.Column('location_alignment', sa.Enum('IN_ALIGNMENT', 'IN_CONTRAVENTION', 'NOT_APPLICABLE', name='locationalignment'), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('denied_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spending_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_channel_id', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('ability_requested', sa.Text(), nullable=True),
    sa.Column('ability_description', sa.Text(), nullable=True),
    sa.Column('ability_limitations', sa.Text(), nullable=True),
    sa.Column('cost_weakness', sa.Text(), nullable=True),
    sa.Column('cost_weakness_description', sa.Text(), nullable=True),
    sa.Column('lore_rule_compliant', sa.Boolean(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('denied_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('UTC_TIMESTAMP()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('earning_submission_id', sa.Integer(), nullable=True),
    sa.Column('spending_submission_id', sa.Integer(), nullable=True),
    sa.Column('admin_transaction_id', sa.Integer(), nullable=True),
    sa.Column('judgement_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_transaction_id'], ['admin_transaction.id'], ),
    sa.ForeignKeyConstraint(['earning_submission_id'], ['earning_submission.id'], ),
    sa.ForeignKeyConstraint(['spending_submission_id'], ['spending_submission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_log')
    op.drop_table('spending_submission')
    op.drop_table('earning_submission')
    op.drop_table('admin_transaction')
    op.drop_table('user')
    # ### end Alembic commands ###
